### ISSUE TITLE
className Prop not functioning properly

### ISSUE THREAD

**Issue by lin-raymond-dev** [buraksakalli/keycap#1]
Classes added to the `className` prop does not get added to class. 

Ex:
`<Keycap activeKey='w' className='someClass text-lg w-48 h-36'>w</Keycap>`
The resulting html is:
`<kbd class='_key_1b3kg_31'>w</kbd>` or `<kbd class='_key_1b3kg_31 _keyPressed_1b3kg_49'>w</kbd>` when pressed.

This prevents custom classes and Tailwind styles from being added to the component.
Feel free to reach out for questions :)

**Comment by buraksakalli** [comment]
Hey @SimplyFlawed,

We just published the new version. Thanks for your consideration.
